### ISSUE TITLE
liveReload Feature

### ISSUE THREAD

**Issue by Yunustuzun** [SAP/grunt-openui5#121]
Hello , 
are there possibility to run as livereload server ? I tried it . But I couldn't success.

**Comment by matz3** [comment]
Yes, you can use the [`livereload` feature of the grunt-contrib-connect task](https://github.com/gruntjs/grunt-contrib-connect#livereload) which is extended by the openui5_connect task. It also takes care of proper handling of LESS / CSS file changes so that they are refreshed in the browser (see [liveReloadLessCssPlugin](https://github.com/SAP/grunt-openui5/blob/7c15d3f550ea2e5f5f4b480ad132ad08359af30b/tasks/connect.js#L26-L52)).
