### ISSUE TITLE
openui5_preload gives no errors but doesn't create anything

### ISSUE THREAD

**Issue by proehlen** [SAP/grunt-openui5#43]
I've experimented with various options in my Gruntfile.js.  If I don't get the paths exactly right, the task complains about no files found.  When I do get the paths right, it runs and says `Done` but doesn't create Component-preload file.  See file structure on left of below screen shot, Gruntfile.js on right and task output bottom-right:

![openui5_preload](https://cloud.githubusercontent.com/assets/8384068/18177857/1d7bae14-70a6-11e6-96d1-bd44604547dd.png)

Any tips or advice would be appreciated.

**Comment by proehlen** [comment]
The above happens when I run the task as an npm-script.  However, I just discovered that if I run it with `grunt-cli` from the command line, I start getting feedback on what the problems are:

![es6](https://cloud.githubusercontent.com/assets/8384068/18193212/977b665a-7105-11e6-887a-41f07c937d93.png)

In the above case, it's unsupported ES6 syntax.  Would still like to know how to configure it so that I get this feedback when running it as a script.

**Comment by proehlen** [comment]
Have switched to a gulp script that I'm having better luck with.  Closing this.

**Comment by matz3** [comment]
Hey @proehlen 
Thanks for your feedback.

The issue with not having any feedback seems to be a duplicate of #36 that has been fixed with #42 (not part of a release, yet).
I can not see any difference between running via `npm run` or `grunt` directly.


When looking at your configuration I would recommend you to adopt a few settings (see comments):
```js
openui5_preload: {
  component: {
    options: {
      resources: {
        cwd: 'public/webapp', // this should point to the entry folder
        prefix: 'meteor-ui5-website', // this should be your component namespace
        src: [
          // src patterns start within the "cwd"
          '**/*.js',
          '**/*.fragment.html',
          '**/*.fragment.json',
          '**/*.fragment.xml',
          '**/*.view.html',
          '**/*.view.json',
          '**/*.view.xml',
          '**/*.properties'
        ],
      },

      // "dest" needs to be defined within "options" not "options.resources"
      dest: 'public/webapp', // to put the file in the same folder

      compress: true
    },
    components: true
  }
}
```
This worked for me when using `grunt-openui5@https://github.com/SAP/grunt-openui5.git#master` (except the ES6 errors with UglifyJS)

PS: I've also had a look into the issue in your repo and why the files from the preload are ignored, but at first glance the file looks correct.

**Comment by proehlen** [comment]
@matz3 Hey thanks very much for your time and the detailed response. I'm able to produce the `Component-preload.js` file using grunt now.  It's still ignoring the preload modules but at least I know I'm doing it the right way now.

**Comment by matz3** [comment]
I've added a comment to the issue in your project.
