### ISSUE TITLE
grunt-openui5 vs grunt-sapui5-bestpractice-build

### ISSUE THREAD

**Issue by immortal-chen** [SAP/grunt-openui5#99]
Hi experts,

there's a similar npm lib `grunt-sapui5-bestpractice-build`, and this [webide guide](https://developers.sap.com/tutorials/webide-grunt-basic.html) tells user to use this one.
Could you tell me what's the difference between `grunt-openui5` and `grunt-sapui5-bestpractice-build`, and how to choose between them?

also, In [ui-tooling](https://github.com/SAP/ui5-tooling), there's a [ui5-builder](https://github.com/SAP/ui5-builder) module, which can also be used to build ui5 project. Which one is the future, any suggestion ?

**Comment by immortal-chen** [comment]
Anyone can help with this question? Thanks!

**Comment by matz3** [comment]
The `grunt-sapui5-bestpractice-build` plugin is using tasks of this project (grunt-openui5) and adds several other tasks and features for building apps and is used by WebIDE projects.

The new [UI5 Tooling](https://github.com/SAP/ui5-tooling) is the successor of the grunt tasks/plugins.
It is also planned to use it for the WebIDE projects in future, so that the features of `grunt-sapui5-bestpractice-build` will be part of the UI5 Tooling or of an extension to it.

I hope this answers your questions.

**Comment by immortal-chen** [comment]
Thank you @matz3 , that was clear to me now.
